### ISSUE TITLE
Missing files when trying to build using make

### ISSUE THREAD

**Issue by vincpad** [ytai/pixie#1]
Hello,

I want to make some modifications in your code so I tried to make a projet in mplabx with your files  but I haven't succeed and since I'm not really comfortable with mplabx I tried another method.
I tried to build it using make but is seems like two files are missing (error message below)
```
Makefile:110: nbproject/Makefile-impl.mk: No such file or directory
Makefile:113: nbproject/Makefile-variables.mk: No such file or directory
make: *** No rule to make target 'nbproject/Makefile-variables.mk'.  Stop.
```
Do you think that you can provide me these files ?

Thanks in advance.
Bye !

**Comment by ytai** [comment]
These files are auto generated by mplab. I'm not sure how portable they would be (for example, might contain paths specific to my machine).
There's no discomfort involved in using mplab. The installation is simple and you don't like using GUI, mplab comes with a command line tool that generates makefile from a project.
